### ISSUE TITLE
Download Issue (https://download.inventivetalent.org/idl/ParticleAPI/2.1.1)

### ISSUE THREAD

**Issue by AtomIsHere** [InventivetalentDev/download.inventivetalent.org#28]
**Which of the 3 download-options were you trying to use?** 
adfly

**Which browser are you using?** 
Brave

**Please describe the issue** 
The first download link (adf.ly) is blocked out

**Please open your browser's console and check it for any errors**  
Found 2 warnings
1. jquery-3.1.1.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery-3.1.1.min.js:4
2. No GoogleAnalytics tracking APIs available
$scope.trackDownloadClick @ script.js:118

**Comment by InventivetalentDev** [comment]
Just disable the ads/trackers blocking in the top right (Brave icon) and you should be good to go c: 
![](https://yeleha.co/2Q8VFbH)
