### ISSUE TITLE
Download Issue (https://download.inventivetalent.org/idl/ResourcePackAPI/2.2.1)

### ISSUE THREAD

**Issue by Dinodudeishgamer** [InventivetalentDev/download.inventivetalent.org#9]
**Which of the 3 download-options were you trying to use?** 
(Please select either adfly/donate/free) 
adfly

**Which browser are you using?** 

Microsoft edge
**Please describe the issue** 

leads me to a blank page
**Please open your browser's console and check it for any errors**  
nope

**Comment by InventivetalentDev** [comment]
Works fine for me. Please try Google Chrome.

**Comment by Dinodudeishgamer** [comment]
[image: Inline image 1]The murder plugin appears red when I try to load it.
I'm using version 1.11.2 spigot and Murder_v3.3.0-SNAPSHOT

**Comment by InventivetalentDev** [comment]
This issue tracker is only intended for problems related to downloading the plugin.  
There is a separate issue tracker for Murder: https://github.com/InventivetalentDev/Murder/issues

**Comment by InventivetalentDev** [comment]
Make sure you have all dependencies installed, btw.
